import {StyleSheet, Dimensions} from 'react-native';

const {width, height} = Dimensions.get('window');
const createStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#6360FF',
    },
    headerContainer: {
      height: height * 0.15,
      width: width,
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      flexDirection: 'row',
      paddingHorizontal: 20,
      position: 'relative',
      paddingBottom: 30,
    },
    body: {
      flex: 1,
      backgroundColor: '#F5F5F5',
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      width: width,
    },
    bodyContent: {
      flex: 1,
      paddingTop: 10,
    },
    searchContainer: {
      width: width - 40,
      height: 50,
      backgroundColor: '#fff',
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      marginVertical: 10,
      alignSelf: 'center',
    },
    searchInput: {
      width: width - 100,
      height: 50,
      backgroundColor: '#fff',
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      marginVertical: 10,
      alignSelf: 'center',
    },
    searchIcon: {
      width: 20,
      height: 20,
      resizeMode: 'contain',
    },
    categoryContainer: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'flex-start',
      paddingHorizontal: 20,
      marginVertical: 10,
      width: width - 100,
    },
    categoryTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#161719',
      marginBottom: 10,
    },
    categoryList: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
      width: width - 100,
    },
    categoryItem: {
      width: (width - 100) / 3 - 10,
      height: 40,
      backgroundColor: '#6360FF',
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
      marginVertical: 10,
      alignSelf: 'center',
    },
    categoryItemText: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    containerText: {
      fontSize: 18,
      color: 'white',
      fontWeight: 'bold',
      backgroundColor: 'rgba(255, 255, 255, 0.17)',
      width: 30,
      height: 30,
      borderRadius: 2,
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      transform: [{rotate: '45deg'}],
    },
    containerBox: {
      backgroundColor: '#FF8181',
      width: 80,
      height: 80,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      shadowColor: '#000',
    },
    subjectItem: {
      width: width - 40,
      height: 100,
      backgroundColor: '#fff',
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingHorizontal: 10,
      marginVertical: 10,
      alignSelf: 'center',
    },
    subjectItemTextContainer: {
      width: width - 150,
      height: 100,
      backgroundColor: '#fff',
      borderRadius: 10,
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'center',
      paddingHorizontal: 10,
      marginVertical: 10,
      alignSelf: 'center',
    },
    subjectItemText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#161719',
      textAlign: 'left',
    },
    subjectItemBranch: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#161719',
      textAlign: 'center',
    },
    subjectItemBranchText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#161719',
      textAlign: 'center',
      paddingLeft: 5,
    },
    subjectItemSem: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#161719',
      textAlign: 'center',
    },
  });

export default createStyles;
